#strings concatinate
str1=input("enter first string:")
str2=input("enter second string:")
str3=str1+str2
print(str3.lower())
print(str3.upper())
print(str3.title())
print(str3.swapcase())
print(str3.capitalize())
print(str3.center(50))
print(str3.casefold())
print(str3.count("n"))
print(str3.endswith("a"))
print(str3.find("a"))
print(str3.isalnum())
print(str3.isdigit())
print(str3.isnumeric())
print(str3.isspace())
print(str3.replace("a","is"))